PACKAGE_NAME="ipu-camera-sensor"
PACKAGE_VERSION="0.1"

MAKE="make KERNELRELEASE=$kernelver KERNEL_SRC=$kernel_source_dir"
CLEAN="make KERNELRELEASE=$kernelver KERNEL_SRC=$kernel_source_dir clean"
AUTOINSTALL="yes"

MODULE_PATH="drivers/media/i2c"
MODULE_DEST="/kernel/drivers/media/i2c/"

BUILT_MODULE_NAME[0]="isx031"
BUILT_MODULE_LOCATION[0]="$MODULE_PATH"
DEST_MODULE_LOCATION[0]="$MODULE_DEST"

BUILT_MODULE_NAME[1]="ar0234"
BUILT_MODULE_LOCATION[1]="$MODULE_PATH"
DEST_MODULE_LOCATION[1]="$MODULE_DEST"

BUILT_MODULE_NAME[2]="ar0830"
BUILT_MODULE_LOCATION[2]="$MODULE_PATH"
DEST_MODULE_LOCATION[2]="$MODULE_DEST"

BUILT_MODULE_NAME[3]="ar0820"
BUILT_MODULE_LOCATION[3]="$MODULE_PATH"
DEST_MODULE_LOCATION[3]="$MODULE_DEST"

BUILT_MODULE_NAME[4]="ar0822"
BUILT_MODULE_LOCATION[4]="$MODULE_PATH"
DEST_MODULE_LOCATION[4]="$MODULE_DEST"
