# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2010 - 2025 Intel Corporation.


obj-$(CONFIG_VIDEO_AR0234) += ar0234.o
obj-$(CONFIG_VIDEO_AR0820) += ar0820.o
obj-$(CONFIG_VIDEO_AR0830) += ar0830.o
obj-$(CONFIG_VIDEO_ISX031) += isx031.o
obj-$(CONFIG_VIDEO_AR0822) += ar0822.o
